### ISSUE TITLE
Decide on Web Framework

### ISSUE THREAD

**Issue by TheFynx** [ImperialLabs/slapi#5]
Sinatra vs Rails

**Comment by aaronblythe** [comment]
I know I have been a vocal fan of using Rails, but with the stuff I have seen in SwaggerHub, I am leaning toward Sinatra now.  The reason is that Rails has helped me scaffold API only apps in the past.  SwaggerHub would fit this need (of scaffolding the code).  Also the ripping out of Rails parts will make for sort of a fight with the SwaggerHub scaffolding.  That being said there may be niceties of pulling in some of the Rails gems if needed over time.

Sinatra +1 from me.

**Comment by aaronblythe** [comment]
Levi and I just had a quick pow-wow on the research we have done so far on Swagger.  The summary has both positives and negatives:
- Benefit: Like the idea of client generation and documentation, so want to continue with Swagger for those aspects.
- Drawback So far our server code gen experience (with ruby sinatra) has not been a very good story.  The code is not rubocop compliant and sort of hack for the routes.
